/**
 * Global-search FEATURE INDEX — the table behind the nav search box (see
 * app/components/GlobalSearch.tsx). Every page, tab and titled section
 * ("feature") of the app is listed here so it can be found by name or keyword
 * and jumped to directly.
 *
 * KEEP IN SYNC: whenever a new page, tab or Card section is added anywhere in
 * the app, add an entry here (see AGENTS.md). Anchors come for free: <Card
 * title="X"> automatically gets id={slugifyAnchor('X')}, so `href:
 * '/page#' + slugifyAnchor('X')` scrolls straight to the card.
 *
 * This module is imported client-side and must stay dependency-free and small —
 * feature matching happens locally on every keystroke (zero-latency), while
 * transaction/merchant/etc. results come from /api/search.
 */

export type SearchTag =
  | 'feature'
  | 'transaction'
  | 'merchant'
  | 'category'
  | 'project'
  | 'goal'

export type SearchResult = {
  tag: SearchTag
  label: string
  /** Where it lives / detail line, e.g. "Budget › Planner" or a date+amount. */
  sublabel: string
  href: string
}

/** Must mirror the id generated by <Card title=...> (app/components/AppShell.tsx). */
export function slugifyAnchor(title: string): string {
  return title
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

type FeatureEntry = {
  label: string
  /** Breadcrumb shown as the sublabel, e.g. "Budget › Planner". */
  page: string
  href: string
  /** Extra match terms beyond the label/page words (lowercase). */
  keywords?: string[]
}

export const FEATURE_INDEX: FeatureEntry[] = [
  // ── Overview ────────────────────────────────────────────────────────────
  { label: 'Overview', page: 'Overview', href: '/', keywords: ['dashboard', 'home'] },
  { label: 'Net trajectory (Month)', page: 'Overview', href: '/#net-trajectory-month', keywords: ['burndown', 'pace'] },
  { label: 'Net trajectory (Year)', page: 'Overview', href: '/#net-trajectory-year', keywords: ['cumulative', 'target', 'december'] },
  { label: 'Goals summary', page: 'Overview', href: '/#goals', keywords: ['savings'] },
  { label: 'Top insights', page: 'Overview', href: '/', keywords: ['cards', 'highlights'] },
  { label: 'Import a statement', page: 'Manage › Import', href: '/manage/import#import-a-statement', keywords: ['upload', 'csv', 'sync'] },

  // ── Budget ──────────────────────────────────────────────────────────────
  { label: 'Budget planner', page: 'Budget › Planner', href: '/budget', keywords: ['plan', 'monthly'] },
  { label: 'Targets', page: 'Budget › Planner', href: '/budget#targets', keywords: ['year-end', 'net', 'goal', 'income'] },
  { label: '50/30/20 rule', page: 'Budget › Planner', href: '/budget#50-30-20-rule', keywords: ['needs', 'wants', 'savings', 'buckets', 'fifty', 'thirty', 'twenty'] },
  { label: 'Category goals', page: 'Budget › Planner', href: '/budget#category-goals', keywords: ['limits', 'envelope', 'suggested'] },
  { label: 'Unavoidable this month', page: 'Budget › Planner', href: '/budget#unavoidable-this-month', keywords: ['fixed', 'bills', 'projected'] },
  { label: 'Spending pace', page: 'Budget › Planner', href: '/budget#spending-pace', keywords: ['run rate', 'projection', 'hot'] },
  { label: 'Bills & projections', page: 'Budget › Bills', href: '/budget/bills', keywords: ['settings', 'recurring'] },
  { label: 'Recurring & subscriptions', page: 'Budget › Bills', href: '/budget/bills#recurring-subscriptions', keywords: ['netflix', 'monthly'] },
  { label: 'Projected bills', page: 'Budget › Bills', href: '/budget/bills#projected-bills', keywords: ['rules', 'cadence', 'insurance'] },
  { label: 'Suggested projection rules', page: 'Budget › Bills', href: '/budget/bills#suggested', keywords: ['auto-detect'] },

  // ── Activity ────────────────────────────────────────────────────────────
  { label: 'Activity', page: 'Activity', href: '/transactions', keywords: ['transactions', 'search', 'list', 'history'] },

  // ── Accounts ────────────────────────────────────────────────────────────
  { label: 'Goals', page: 'Accounts › Goals', href: '/accounts', keywords: ['savings', 'mortgage', 'kitchen', 'invest', 'contribute'] },
  { label: 'Emergency Fund', page: 'Accounts › Emergency', href: '/accounts/emergency#emergency-fund', keywords: ['chequing', 'balance', 'tfsa'] },
  { label: 'Emergency runway', page: 'Accounts › Emergency', href: '/accounts/emergency#emergency-runway', keywords: ['job loss', 'months', 'scenario'] },
  { label: 'Safe to move to investment', page: 'Accounts › Emergency', href: '/accounts/emergency#safe-to-move-to-investment', keywords: ['cash flow', 'trough', 'transfer'] },
  { label: 'Investments', page: 'Accounts › Investments', href: '/accounts/investments', keywords: ['tfsa', 'resp', 'room', 'grant', 'cesg', 'holdings', 'itrade', 'contribution'] },
  { label: 'Net worth', page: 'Accounts › Net worth', href: '/accounts/networth#net-worth', keywords: ['total', 'assets'] },
  { label: 'Mortgage remaining', page: 'Accounts › Net worth', href: '/accounts/networth#mortgage-remaining', keywords: ['payoff', 'balance', 'house'] },

  // ── Reports ─────────────────────────────────────────────────────────────
  { label: 'Trends', page: 'Reports › Trends', href: '/reports', keywords: ['charts', 'spending'] },
  { label: 'Monthly spend', page: 'Reports › Trends', href: '/reports#monthly-spend', keywords: ['bar chart'] },
  { label: 'By category', page: 'Reports › Trends', href: '/reports#by-category', keywords: ['breakdown'] },
  { label: 'Month over month', page: 'Reports › Trends', href: '/reports#month-over-month', keywords: ['compare', 'delta'] },
  { label: 'Where it went', page: 'Reports › Trends', href: '/reports#where-it-went', keywords: ['top spend'] },
  { label: 'Top merchants', page: 'Reports › Trends', href: '/reports#top-merchants', keywords: ['vendors', 'stores'] },
  { label: 'Spending by weekday', page: 'Reports › Trends', href: '/reports#spending-by-weekday', keywords: ['day of week'] },
  { label: 'New & unusual', page: 'Reports › Trends', href: '/reports#new-unusual', keywords: ['anomaly', 'first time'] },
  { label: 'Income', page: 'Reports › Income', href: '/reports/income', keywords: ['salary', 'pay', 'sources'] },
  { label: 'Income by source', page: 'Reports › Income', href: '/reports/income#income-by-source', keywords: ['employer', 'deposit'] },
  { label: 'Cash flow', page: 'Reports › Cash flow', href: '/reports/cashflow#cash-flow', keywords: ['sankey', 'money flow', 'diagram'] },
  { label: 'Subscriptions', page: 'Reports › Subscriptions', href: '/reports/subscriptions', keywords: ['recurring', 'watchdog'] },
  { label: 'Price changes to review', page: 'Reports › Subscriptions', href: '/reports/subscriptions#price-changes-to-review', keywords: ['increase', 'creep', 'alert'] },
  { label: 'Subscription spend by month', page: 'Reports › Subscriptions', href: '/reports/subscriptions#subscription-spend-by-month' },
  { label: 'Where the money goes (per year)', page: 'Reports › Subscriptions', href: '/reports/subscriptions#where-the-money-goes-per-year', keywords: ['annualized'] },
  { label: 'Custom reports', page: 'Reports › Custom', href: '/reports/custom', keywords: ['build', 'series', 'lines'] },
  { label: 'Saved reports', page: 'Reports › Custom', href: '/reports/custom#saved-reports', keywords: ['pinned'] },
  { label: 'Where to cut', page: 'Reports › Custom', href: '/reports/custom#where-to-cut', keywords: ['trim', 'reduce'] },

  // ── Recap ───────────────────────────────────────────────────────────────
  { label: 'Monthly recap', page: 'Recap', href: '/report', keywords: ['80s report', 'month report', 'grade', 'summary'] },

  // ── Manage ──────────────────────────────────────────────────────────────
  { label: 'Categories', page: 'Manage › Categories', href: '/manage', keywords: ['edit', 'colors', 'buckets', 'kind'] },
  { label: 'Merchants', page: 'Manage › Merchants', href: '/manage/merchants', keywords: ['rules', 'merge', 'rename', 'learning'] },
  { label: 'Projects', page: 'Manage › Projects', href: '/manage/projects', keywords: ['trip', 'reno', 'group', 'overlay'] },
  { label: 'Notifications', page: 'Manage › Notifications', href: '/manage/notifications#notifications', keywords: ['push', 'digest', 'alerts'] },
  { label: 'Feedback tracker', page: 'Manage › Feedback', href: '/manage/feedback', keywords: ['bugs', 'ideas', 'todo'] },
]
